### ISSUE TITLE
Dark mode problem

### ISSUE THREAD

**Issue by massimopagani** [lodauria/AudioSpeedUp#14]
![Screenshot_20200404-102326 1](https://user-images.githubusercontent.com/58979455/78422307-a9714e80-765e-11ea-8a16-a98c5ba94b84.png)

**Comment by ghost** [comment]
I know that the dark theme has some problems, this is not the only one.
Please be patient for more stable version in the future, but since this is not a job for me I don't have time to work on this app full time.
Anyway thanks for the report

**Comment by ghost** [comment]
Solved in the last release.
