### ISSUE TITLE
Test button

### ISSUE THREAD

**Issue by NotAndreh** [lodauria/AudioSpeedUp#27]
The first click on the test button starts the audio fine, but if you use the stop button and click again on the test button the app crashes.

**Comment by ghost** [comment]
On which version of Android?

**Comment by NotAndreh** [comment]
OnePlus 6 with Android 10

**Comment by ghost** [comment]
Ok, solved

**Comment by GLWine** [comment]
I wanted to warn you of the same problem on Android 8.1, however it has been resolved with your latest update

**Comment by ghost** [comment]
Yes, thank you both for the reporting!
