### ISSUE TITLE
Spotify integration

### ISSUE THREAD

**Issue by lucaguarro** [lodauria/AudioSpeedUp#30]
How difficult would it be to add a feature that allows integration with Spotify?

**Comment by lodauria** [comment]
I would say quite impossible. The problem is that Spotify doesn't save songs as standard MP3 (or similar) files due to copyright reasons. Open those files from a different app it is purposely made impossible.

**Comment by lucaguarro** [comment]
Just thought I'd ask since paid apps like "Amazing Slow Downer" offer this. Would be cool to have an open-source version. I know that Spotify makes it hard but I don't know the specifics of what they do
